### ISSUE TITLE
Identical redirect uri not matching up during oauth

### ISSUE THREAD

**Issue by melinath** [Dwolla/dwolla-python#19]
I'm getting the following error during oauth:

```
Redirect Uri does not match redirect uri associated with token.
```

The only problem is that the redirect URIs that I'm providing to the library functions *do* match. I've checked. They take the format `http://domain.com/path/?next_url=/finished/` (roughly). I suspect that there might be an escaping issue somewhere in the library itself, but I'm having trouble figuring out the best way to debug this, since I can't easily check what redirect_uri is *actually* associated with the oauth code I receive - only what redirect_uri I provided.

**Comment by mach-kernel** [comment]
That's really strange. I'm going to test this on my end and see what comes up. Can you do me a small tiny favor? Would you be able to provide the `redirect_uri` in the form of the full URL? I realize this sounds kind of un-necessary but I'm curious to see if it'll behave differently.

Our API's serializer uses the URI format and it may be coming back as invalid due to the lack of the whole `http://whatever.net/place`. Just a thought. I'll look into this, thanks for the bug submission!

**Comment by mach-kernel** [comment]
@melinath,

I've found the issue. The `requests` library is choking on urlencoding something properly, however, if a urlencoded string is passed to it (e.g it tests for off characters) then it will ignore it. I tried urlencoding everything myself and the request gets processed. I'm going to urlencode via urllib and push out a patch to fix this. Expect it within the next 30 minutes. 

David

**Comment by melinath** [comment]
@mach-kernel The redirect_uri is `http://domain.com/path/?next_url=/finished/`. That whole string (including the querystring) is the redirect_uri. next_url is a variable I use internally to redirect after oauth completes. (I also pass along some other state data this way.)

**Comment by melinath** [comment]
My best guess was that the library might not handle redirect_uri values that contain querystrings very well.

**Comment by melinath** [comment]
Ah! Just got your second reply. Great! Thanks.

**Comment by mach-kernel** [comment]
@melinath 

Sorry for the late reply, but I pushed the changes out a couple of hours ago. I hope it works!

**Comment by melinath** [comment]
Yep, works now. Thanks!
